name = "Seeker Camp"
author = "MementoInAbyss contributors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a4ef3d01bc85f6403e5df78aa88610f95b8c36702b82f8c5ca440b3c7b7f3eb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["h"]
